---
# Для запуска основной задачи, регулируемой ключом [-a|--action], GO-DTS подготавливает дополнительные переменные, необходимые для её корректного запуска.
# Результирующий набор аргументов формируется на основе переданных приложению (входящих) аргументов командной строки.
# До версии GO-DTS v0.6 вспомогательные переменные генерировались только на основе (входящих) аргументов командной строки,
# а сама функция, отвечающая за генерацию переменных, не учитывала возможность их изменений.
# В версии GO-DTS v0.6 при наличии конфигурационного файла, go-dts заменит входящие аргументы командной строки содержимым файла custom_args.yml.
# Конфигурационный файл custom_args.yml позволяет произвольно заменять исходные значения аргументов,
# в случае генерируемых переменных, передаваемые значения не проверяются на соответствие исходным (входящим или кастомным) аргументам,
# Данная возможность добавляет гибкость при отладке приложения в различных условиях, пример:
# данная функция, путем замены аргументов, позволяет имитировать запуск приложения на текущей машине с "окружением", хорактерным
# для выбранной машины (примеры изменяемых значений: платформа, имя хоста, параметры etcd, хеши, не зависящие от расположения target приложения или агента...).

args:
  # replacement for command-line args 
  action: "init"
  work_tree: "C:/test"
  dts_dir: "C:/gitdir"
  instance: "3082379100" # instance is a crc32 hash of the path to target application (type: string!)

